<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sergey-pc" name="Command line test" tests="3" failures="1" timestamp="28 May 2018 08:52:55 GMT" time="0.029" errors="0">
  <testcase name="firstMethod" time="0.011" classname="sampl.SampleTest"/>
  <testcase name="secondMethod" time="0.0" classname="sampl.SampleTest"/>
  <testcase name="thirdMethod" time="0.002" classname="sampl.SampleTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at sampl.SampleTest.thirdMethod(SampleTest.java:26)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- thirdMethod -->
</testsuite> <!-- Command line test -->
