<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sergey-pc" name="Surefire test" tests="3" failures="1" timestamp="28 May 2018 08:59:17 GMT" time="0.027" errors="0">
  <testcase name="firstMethod" time="0.008" classname="sampl.SampleTest"/>
  <testcase name="secondMethod" time="0.0" classname="sampl.SampleTest"/>
  <testcase name="thirdMethod" time="0.001" classname="sampl.SampleTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at sampl.SampleTest.thirdMethod(SampleTest.java:26)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- thirdMethod -->
</testsuite> <!-- Surefire test -->
